### ISSUE TITLE
建议四舍五入一下坐标

### ISSUE THREAD

**Issue by Linus0080** [Yuameshi/leica-generator#1]
![psc5 jpeg-Leika](https://user-images.githubusercontent.com/66841417/178100644-377b3e46-098f-428f-b7be-2970e229a631.jpg)
如图，坐标把可乐标都顶没了qwq

**Comment by yuameshi** [comment]
草，马上

**Comment by yuameshi** [comment]
你再试试，应该可以了

**Comment by Linus0080** [comment]
> 你再试试，应该可以了

好，可以了
![Uploading PXL_20220709_101057820.MP_exported_499.jpg-Leika~2.png…]()

**Comment by Linus0080** [comment]
![PXL_20220709_101057820 MP_exported_499 jpg-Leika~2](https://user-images.githubusercontent.com/66841417/178102247-cb7ea75d-130c-4a11-b080-1c4754e34d82.png)
可（
